### ISSUE TITLE
Crash on WeatherViewModel 

### ISSUE THREAD

**Issue by shrawan2015** [marinbenc/ReactiveWeatherExample#3]
![screen shot 2016-08-30 at 10 42 32 am](https://cloud.githubusercontent.com/assets/10405305/18076809/93265272-6e9e-11e6-9cb2-f07ef7bfacd6.png)

**Comment by jengelsma** [comment]
Ditto, I'm seeing the same.  Hmm...  looks like he forgot to include the 19th icon code!   See pull request for fix.

**Comment by shrawan2015** [comment]
Ok,Thanks .

**Comment by marinbenc** [comment]
Thanks @jengelsma for the pull request and @shrawan2015  for noticing the issue.
